### ISSUE TITLE
Mention random in text?

### ISSUE THREAD

**Issue by javl** [inconvergent/shepherd-js#1]
At **Sums of Velocities** it says:
    
    the velocity of a given node is the sum of all 
    the velocities of the nodes on it's left hand side.

Shouldn't this be "the sum (...) plus a bit of random noise"? If you only use the value of the previous nodes you would end up with a straight line (plus the first node needs some initial velocity for the others to use), right?

**Comment by inconvergent** [comment]
not quite. but you are right that this is not entirely well phrased. i'll look at it.

**Comment by inconvergent** [comment]
i updated the section. it is live on the web, and the commit is here https://github.com/inconvergent/shepherd-js/commit/543ee8a30fc57c71b3f027fab7f193e20e60f641

**Comment by javl** [comment]
Thanks for clarifying. 
Minor typo in the text:
    So here is **a one** possible way to change that

**Comment by inconvergent** [comment]
yeah, thanks, i've already fixed it in the dev branch. not pushed yet.
